- src/tables/cff.js
Issue #85 reported malformed characters displayed from two OTF font files.
Investigation found that the CFF CharString instructions in these fonts
employed the rather unusual operator 'flex1', which was not implemented
by opentype.js.  About 8 out of 300+ characters used the operator.
Upon encountering the 'flex1' operator the code would simply skip over
the operator.  This resulted in the accumulated operand values being
left on the stack, which disrupted execution of following operators, and
left the affected characters obviously distorted.  Clearing of the stack
when an unsupported operator is found was added to fix that.
This still left the characters distorted because one of the drawing
instructions was missing.  (In this case the missing part was vertical
so the resulting curves …
> Add CFF Type 2 CharString operator 'flex1'

- src/tables/cff.js
I've expanded on @tshinnic's groundwork and added support for the remaining flex operators. Relates to issue #85.
> Add support for the remaining CFF Type 2 CharString flex operators (flex, hflex and hflex1)

- package.json
Before this change, npm install would give the following warning:
$ npm install
npm WARN package.json opentype.js@0.4.8 No license field.
According to https://docs.npmjs.com/files/package.json#license
"licenses" has been deprecated by "license".
> Use SPDX license identifier

- font-inspector.html
- glyph-inspector.html
While debugging it is very useful to have all possible information in
the rare (cough!) event of an exception.  While both the font-inspector
and the glyph-inspector were notifying the user of exceptions via the
web page, the additional information useful to developers was not seen.
This change adds logging of an exception's stack information to these
two web pages.  Previously little or nothing would be seen in a browser's
debug console window:
(font-inspector)
```
A CID Font!
```
(glyph-inspector)
```
A CID Font!
Uncaught ReferenceError: xxfont is not defined  glyph-inspector.html:381
```
This change adds logging of the exception along with stack information:
```
A CID Font!
ReferenceError: xxfont is not defined           glyph-inspector.html:380
at Object.parseCFFTable [as parse] …
```
> Add console.log stack dumping

- test/opentypeSpec.js
PostScript (a.k.a. Type 1) is a different thing.
> Correct font format terminology.

- src/types.js
- test/testutil.js
- test/types.js
sizeOf.NUMBER16, sizeOf.NUMBER32: Fix off-by-one errors
encode.UTF16: Handle all Unicode characters, even when not in ISO 8859-1
sizeOf.CHAR: Implement, as it was hidden by a typo
sizeOf.OBJECT, sizeOf.TABLE: Implement missing functions
> Fix buggy encodings of basic types

- src/tables/name.js
- src/types.js
- test/types.js
Supports only those character encodings that need little data for
conversion. Decoding strings is fast and allocates hardly any memory.
Encoding strings is less cheap, but rarely needed; the necessary
encoding tables get cached in a WeakMap (if the VM supports this).
Fix a race condition in encoding.CHARSTRING (related to WeakMap).
> Implement MACSTRING codec

- src/opentype.js
- src/tables/ltag.js
- src/tables/name.js
- test/tables/ltag.js
The ‘ltag’ table contains IETF BCP-47 language tags, so fonts can
support arbitrary languages. It is basically Apple’s version of what
Microsoft did in “format 1” naming tables of OpenType.
In a later change, I will modify the ‘name’ parser so it actually uses
these language tags (if people are fine with this plan). It should be
straightforward to support both the Apple and the Microsoft way.
See also https://github.com/nodebox/opentype.js/issues/144 for context.
> Parse ‘ltag’ table, and pipe it through to name.parse()

- font-inspector.html
- src/opentype.js
- src/tables/fvar.js
- test/tables/fvar.js
- test/testutil.js
This table is part of Apple’s Advanced Typography, not OpenType; so
this might be considered out of scope for the opentype.js project.
On the other hand, the FreeType project has implemented AAT variation
axes, so the utility goes beyond MacOS. If opentype.js was fine with
accepting changes for AAT tables, I would implement the ‘avar’ and
‘gvar’ tables in subsequent changes.
> Support ‘fvar’ tables for variable fonts

- src/tables/name.js
- src/types.js
- test/types.js
The previous implementation was probably incorrect for codepoints
above U+7FFF, since it was parsing signed 16-bit numbers. The new
version uses unsigned 16-bit integers, and has a unit test.
> Move UTF16 decoding to types

- src/tables/name.js
- src/types.js
- test/types.js
Callers of MACSTRING.encode and MACSTRING.decode should not
be burdened with managing the String objects that WeakMap
requires for its keys; this is an implementation detail that
makes the API rather complex. Instead, the implementation
is now managing these String keys internally.
> Simplify MACSTRING interface

- examples/creating-fonts.html
- examples/reading-writing.html
- font-inspector.html
- site.css
- src/font.js
- src/opentype.js
- src/tables/name.js
- src/tables/sfnt.js
- test/opentypeSpec.js
- test/tables/name.js
This change affects the public API to OpenType.js: Instead of
`familyName`, the English font family name is now stored as
`names.fontFamily.en`, the Spanish name as `names.fontFamily.es`,
and so on. Likewise for all other names stored in a font.
OpenType names are rather complex to interpret. The API hides this
complexity; language codes are exposed as IETF BCP 47 language tags,
which most web programmers already know from HTML and XML.
Resolves https://github.com/nodebox/opentype.js/issues/144.
Screenshot:
> Support multilingual names

- src/opentype.js
- src/tables/fvar.js
- test/tables/fvar.js
Before this change, a client would have to look up the nameID
in the font’s naming table when parsing a font.  Now, the names
are directly available from the axis and instance objects.
> Handle names of font variation axes and instances

- README.md
opentype.js already supports SVG path.
I add description for SVG support to `README.md` because it works well.
> Add description for SVG support to README.md

- src/opentype.js
Fixes #140
The hmtx table was parsed only for TTF fonts. For OTF/CFF fonts, the glyphs advanceWidth was calculated only after lazy-loading of the path, resulting in NaN values.
This may be impacted by #135.
> Fixes #140

- src/font.js
font.getPaths() creates an array of Path objects that represent the glyps of a given text. This comes in quite handy if you would like to manipulate single chars in a text string later on.
> Added: font.getPaths()

- src/table.js
- src/tables/cff.js
- src/tables/name.js
- src/tables/sfnt.js
- src/types.js
- test/types.js
This introduces a new class `Record` and the associated type `RECORD`.
It is used to group fields together and provides a `sizeOf` method.
Differences with Table:
* the data is inlined alongside other fields, whereas Table data is stored after all other fields and referenced via an offset.
* this structure is not meant to be recursive
> Fix regression introduced by #175

- font-inspector.html
- site.css
The [font inspector demo](http://opentype.js.org/font-inspector.html) `cmap` currently displays `[object Object]` as the value of `glyphIndexMap`.
This PR replaces that with the actual object & adds `word-break: break-all;` to the css to make all the text wrap. Also, in the `fvar` is usually undefined, so an "Undefined" message is now shown.
Also, in case you're interested, I created [a userscript](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-font-preview) that uses opentype.js to add a font preview on git font file pages. I blatantly copied the font & glyph inspector code - I hope you guys don't mind.
> Show cmap.glyphIndexMap object & text wrap output

- src/tables/sfnt.js
Hi 😉
I just fixed a bug with the usFirstCharIndex see reports from Microsoft's Font Validator:
`E2130 	The usFirstCharIndex is not valid -	actual = 0x0000, calculated = 0x0020`
After fixing it:
`P2100 	The usFirstCharIndex and usLastCharIndex fields are valid -  first = 0x0020, last = 0x005f`
> Fix OS/2 usFirstCharIndex

- src/font.js
- src/layout.js
- src/substitution.js
- test/substitution.js
As discussed in #194, this is the beginning of an API to edit the data in in the `font.tables.gsub` object.
`font.substitution.getFeature()` returns a list of entries in lookup 4 (ligature) tables.
`font.substitution.add()` can add entries in lookup 4 tables.
More lookup types can be added.
> GSUB table edition

- src/encoding.js
If a font file doesn't have font.glyphNames.names then function
addGlyphNames(font) throws an error "TypeError: Cannot read property '0'
of undefined"
> No glyph names fix

- src/table.js
- src/tables/gsub.js
- src/tables/sfnt.js
- test/parse.js
- test/substitution.js
- test/tables/gsub.js
Adds simple GSUB writing capabilities.
- Common Layout Tables writing is exposed in `table.js` to be reused with other tables (mostly)
- Only lookup type 1 format 1 (single substitution) and lookup type 4 (ligature)
- Only Coverage format 1 (individual glyphs)
- Only DFLT script and defaultLangSys
> (limited) GSUB writing

- src/font.js
- src/tables/name.js
I added an error when a name table entry is not existing, like doing a typo an a name: ~~fontSubFamily~~ (typo on uppercase F), the good name is "fontSubfamily"!
Before throwing the error the font was still looking "good" so it was a nightmare to debug it!
\+ Improve throw error message of Font.download()
Before
After
> Better errors!

- glyph-inspector.html
- src/tables/glyf.js
See https://www.microsoft.com/typography/otspec/glyf.htm
> Argument1 and argument2 can be either x and y offsets to be added to the glyph or two point numbers. In the latter case, the first point number indicates the point that is to be matched to the new glyph. The second number indicates the new glyph's “matched” point. Once a glyph is added, its point numbers begin directly after the last glyphs (endpoint of first glyph + 1).
> Support glyf table component offset by matched points

- src/font.js
HTML Letter-spacing is added or subtracted between every characters in a string of text. Letter Spacing is usually declared in ems. Graphics Software uses the term Tracking, and [multiplies the ems by 1000](http://stackoverflow.com/a/36612356/6465140) to avoid working in decimals.
> Add support for letter spacing / tracking

- src/font.js
To redefine path where font is generated, for example, `font/fontName.otf` to place font to a directory
> Take optional filename argument in download

- src/path.js
I added a function, that returns an svg path as an html element, so you can add your newly rendered path straight into specific DOM element, without struggling with string parsing.
[Codepen Demo here.](http://codepen.io/jakub_antolak/pen/zNYMeK)
> Convert the path to a SVG <path> element as a html element

- .travis.yml
Version 0.10 has reached its end of life and is not maintained anymore.
https://github.com/nodejs/LTS#lts-schedule
> Upgrade Travis configuration to node.js version 6

- README.md
- externs/opentype.js
- glyph-inspector.html
- index.html
- site.css
- src/font.js
- src/layout.js
- src/substitution.js
- src/tables/gpos.js
- test/font.js
- test/layout.js
- test/substitution.js
Add GSUB "liga" and "rlig" rendering support.
Solves #236, #230 and also #245.
Glyph rendering options are added to enable each GSUB feature individually.
Only "liga" and "rlig" are supported, and enabled by default as the spec suggests.
A "ligatures" checkbox is added to `index.html`.
Plus a small layout improvement to the glyph-inspector.
This is open for comments, especially on the options API :-)
> Add ligature rendering

- index.html
- src/font.js
- src/glyph.js
- src/hintingtt.js
- src/opentype.js
- src/parse.js
- src/tables/glyf.js
Implementing a font hinting interpreter for truetype:
Demo:
The actual canvas is the top one, the lower one has each pixel enlarged by a factor of 7.
The font used in the demo is DejaVuSans.ttf
First line is default opentype.js
Second line is opentype.js with fonthinting enabled
Third line is canvas.fillText() with @font-face.
As you see there is hardly a difference between second and third line, except glyph advancement not being hinted. I didn't do that yet, as that would require some changes to the opentype.js.
I tried to keep all changes to opentype.js outside of src/hintingtt.js as minimal as possible. 
PS: I'll need to append a fix commits until the code styling checks stop complaining.
> Truetype Font Hinting

- src/tables/glyf.js
- test/opentypeSpec.js
TrueType glyph outlines were not being closed properly; only a single closePath command was being issued for each glyph.  This fix ensures that a closePath command is issued for each contour.
> Fix unclosed paths for TrueType glyphs.

- dist/opentype.js
- src/opentype.js
https://github.com/nodebox/opentype.js/issues/275
An error was being thrown in parseBuffer(...) when calling parseShortList(...) due to a discrepancy in how parseOpenTypeTableEntries(...) & parseWOFFTableEntries(...) returns values. This ended up throwing an error when parsing any WOFF font that includes a cvt table.
parseShortList(tableEntry.length / 2) was expecting tableEntry to have a length, but the WOFF parser only returns the values compressedLength and originalLength so tableEntry.length ends up equalling undefined. This ends up throwing an error when new Array(count) is being called in parseShortList(...)
I ran through `npm test run`. I tested again previously failing fonts.
> Fix discrepancy in tableEntries #275

- src/font.js
`Font.getPath` was passing along `options` and `this` but `Font.getPaths` is hitting the same endpoint without those arguments.
I added the `options` object and `this` onto the arguments for `glyph.getPath`
This fixes using options on `Font.getPaths` so that it works the same as `Font.getPath`. The specific issue I was having was that hinting wasn't being applied.
I ran it and it worked. I didn't test too vigorously because it seems like it was just an overlooked change when hinting was added. If there's a good way to unit test this I'm open to suggestions.
> Fix Font.getPaths to pass along options and this

- src/parse.js
- test/tables/gsub.js
A lot of fonts have been seen with GSUB tables containing only NULL pointers.
Null pointers in GSUB sublists are now converted to empty lists instead of undefined.
Fixes #254 
Tested against all fonts reported in #254 (LeagueGothic, Gabriela, Cutive Mono).
Added a unit test.
> Better parsing of NULL pointers (#254)

- src/glyph.js
In some cases (e.g. whitespace glyphs on Gabriela) this could lead to a
"glyph.path.toPathData is not a function" error, because glyph.path was not an instance of Path.
Gabriela:
https://fonts.gstatic.com/s/gabriela/v6/qkBWXvsO6sreR8E-b8m5xL0.woff
> Fix bad path init

- bin/test-render
Rendering tests at https://github.com/unicode-org/text-rendering-tests fail, probably because Node doesn't like the "import" statement in the src/ files ("SyntaxError: Unexpected token import")
Redirecting the require to the compiled file in dist/ solves it.
Command-line `node ./bin/test-render --font=fonts/FiraSansOT-Medium.otf --testcase=TEST-1 --render=BALL`
> Fix rendering test

- src/font.js
- src/layout.js
- src/opentype.js
- src/parse.js
- src/position.js
- src/tables/gpos.js
- test/layout.js
- test/parse.js
- test/tables/gpos.js
Full rewrite of the old GPOS table parser.
* exposes raw data in font.tables.gpos
* code is simpler and consistent with the GSUB parser, with less duplication
* better kerning
Fixes #292 and maybe other reported issues.
* only lookups 1 (single glyph positioning) and 2 (pair positioning) are parsed
* kerning rendering still limited to xAdvance
* extended tables (lookup 9, uses e.g. in Times New Roman) still not supported
* no writing
New unit tests added. Tried the home page with at least a dozen various fonts.
> Rewrite GPOS parsing

- src/font.js
- src/opentype.js
- src/position.js
Fix #332 (API break introduced by #323)
> Restore simple GPOS kerning in font.getKerningValue

- src/tables/gpos.js
A `check.assert` assertion was placed too late and failed to detect a case of malformed font.
> GPOS: display correct error message in some cases of malformed data

- bin/test-render
- package.json
- src/encoding.js
- src/font.js
- src/opentype.js
A new pull request after changing the code per the comments in #331.
Replaced `charCodeAt()` to `codePointAt()`  in `encoding.js` and modified `font.js` to handle surrogate pairs, for supporting non-Basic-Multilingual-Plane characters (i.e. `U+10000` to `U+10FFFF`).
It addresses #168 and #327, and the issue mentioned by @schuylr in #297.
1. `npm run test`
2. `npm run dist` and `npm run start` to check the usages of `opentype.js` via `http://localhost:8080`
3. Run the rendering test from https://github.com/unicode-org/text-rendering-tests. After the fix, it passed `CFF-1` and `CFF-2` test cases. Results in `GVAR-4`, `GVAR-5` and `GVAR-6`
4. Tested in Internet Explorer 11 for the polyfill of `String.prototype.codePointAt`
are still incorrect, but the icon is shown instead of 2 dots. See the …
> Support non-Basic-Multilingual-Plane (BMP) characters

- src/font.js
Whitespace characters are illegal in postScriptName and will result in
the font file being flagged as corrupt/invalid (at least on Windows 10).
Since all other fields are copied as-is from the options initialization
parameter without additional validation, I'm only stripping whitespace
in the case that opentype.js generates the postScriptName field
automagically from two other fields that _don't_ have the same
no-whitespace restriction.
> Prevent auto-generated postScriptName from containing whitespace

- src/tables/cmap.js
Adds support for cmap platformId, encodingId:
* [0, 0] Unicode, Default semantics
* [0, 1] Unicode, Version 1.1 semantics
* [0, 2] Unicode, ISO 10646 1993 semantics (deprecated)
* [0, 3] Unicode, Unicode 2.0 or later semantics (BMP only)
* [0, 4] Unicode, Unicode 2.0 or later semantics (non-BMP characters allowed)
Issue #348
`npm test` and `npm start` (dropping a couple of fonts including that from #348)
> Parse cmap table with platform 0 as well

- src/font.js
Currently `Font.download` utilizes `window.requestFileSystem` to save a file.  This method only works on Chrome (13+) and Opera (15+).  It's also non-standard.
Over at Glyphr Studio, we implement a method that uses `window.URL`, which works on a larger set of browsers : Chrome (32+), Opera (19+), Firefox (26+), Safari (7.1+), and all of Edge.
In the past I've been taking the opentype.js dist file and modifying it to use this method before I include it in Glyphr Studio - which is silly 😄 
Loaded a font into the development server and tried `font.download();` on FireFox, Chrome, Opera, and Edge on Windows 10.  Used Browser Stack to test Safari on Mac.
> font.download() uses window.URL instead of window.requestFileSystem

- README.md
- src/opentype.js
Hello + Thank you for your wonderful work with Opentype. It's a wonderful library.
Feel free to reach out with any questions or comments. 
Adds a small conditional to the `.load()` function to support and `promises` and `async/await` for loading font files in the browser. 
Usage looks like:
For promises:
```js
opentype.load('fonts/my-wonderful-font.otf').then( font => {
console.log(font)
});
```
For async/await:
```js
async function make() {
try {
const font = await opentype.load('fonts/PublicSans-Regular.otf');
console.log(font)
} catch (err) {
console.log(err);
}
}
make();
```
This change can make help resolve visual callback craziness and may enhance user experience. Also it may be nice as a way of cleaning up code for teaching and workshops. 
* Tested in Firefox and Chrome
Same …
> Adds support for browser Async/Await for .load()

- package.json
- rollup.config.js
This PR introduces `opentype.module.js`, a single build file representing the lib as a ES6 module.
The new dist file is configured in `rollup.config.js`. Besides, the `module` property of `package.json` now points to it (and not the `src/opentype.js` anymore).
We the `three.js` team currently convert our example codebase to ES6 modules. We also use `opentype.js` in one of our [loaders](https://threejs.org/examples/webgl_loader_ttf). However, it still depends on the `opentype.js` UMD version. Since we copy build files to our example directory, it's not possible to use `npm` and the exports from [src/opentype.js](https://github.com/opentypejs/opentype.js/blob/master/src/opentype.js).
I've tested the new build file with `THREE.TTFLoader` and the respective example.
> Introduce ES6 module build.

- .travis.yml
I just updated the dev dependencies and they won't work with Node 4 anymore.
So I'm removing it from Travis and Node 10 will be the only version tested from now.
Let me know if you see any issue with that ;-)
> Remove Node 4 from Travis

- src/opentype.js
- test/opentypeSpec.js
Fixes the incomplete Promise / async/await support for the load function – the initial implementation did not support using `reject` for problem paths and always attempted to use the potentially null `callback` instead.
Fixes #406
Additional unit tests to cover existing feature and prove bug existence & resolution.
n/a
> Fix use of Promise / async/await in the load function

- src/glyph.js
If you generate a glyph with options evaluating falsy the values are not stored in the object.
Reproduce:
```js
// ZERO WIDTH SPACE (U+200B)
new Glyph({
name: "uni200B",
unicode: 8203,
advanceWidth: 0,
path: new Path()
})
```
> fix GlyphOptions with falsy values

- src/substitution.js
Some minor fixes to doc comments and error messages. Lookup type ids were incoherent and all error messages began with "Ligature:" regardless of type. Also, type 1 of 
I found those wrong messages a bit confusing when I encountered them while working on the implementation for GSUB lookup type 2 (Multiple Substitution). Might confuse other contributors and users as well.
Just some minor textual changes.
> minor cleanup on doc comments and error messages

- src/opentype.js
- src/tables/gdef.js
- test/tables/gdef.js
This adds a class to parse the GDEF table. I need this because I'm needing to show the difference between mark and base glyphs in [an application](https://github.com/simoncozens/crowbar).
There's currently no interface to the data yet, because I would appreciate some guidance on how you would like to do it. It seems obvious to me that the GDEF table provides properties on `Glyph` objects, and so I would imagine something like this in `GlyphSet.prototype.get`:
```
this.glyphs[index].glyphClass = Layout.prototype.getGlyphClass(this.font.tables.gdef.classDef, index)
```
But do we really want to load glyph classes every time a glyph is instantiated?
> Add support for parsing GDEF table

- src/table.js
- test/tables/gsub.js
Implements writing of coverage tables in coverage format 2, which uses glyph ranges instead of a list of glyphs, see https://docs.microsoft.com/de-de/typography/opentype/spec/chapter2#coverage-format-2.
Loading a font that contained a coverage table with coverage format 2 and trying to save it failed with the error message
> Can't create coverage table format 2 yet.
Loaded a font that contains at least one coverage table with coverage format 2 (e.g. this [test font](https://github.com/opentypejs/opentype.js/files/5403238/testfont_coverage_format_2.zip) i created) and save it (using `font.download()` or `font.toArrayBuffer()`). It will fail before the fix and work fine afterwards. I verified that the lookup table is still in the file and it opens fine using Windows Font viewer and …
> implement writing of coverage format 2

- src/tables/cff.js
As specified by [CFF specification](https://typekit.files.wordpress.com/2013/05/5176.cff.pdf) (see page 24), the defaultWidthX and nominalWidthX operators should have a default value of 0.
`gatherCFFTopDicts` parses the CFF table's DICT data. It is in charge of assigning correct defaults for the private DICT operator _subrs_. I assumed we would like to also initialize the default values for __defaultWidthX_ and __nominalWidthX_ here, since other calculations rely on there always being  a value for the topDict's __defaultWidthX_ and __nominalWidthX_.
This solves the problem of OTF fonts that don't have a private DICT having all glyphs end up with a width of NaN, since the width calculation expects values for __defaultWidthX_ and __nominalWidthX_.
- …
> Initialize CFF DICT's _defaultWidthX and _nominalWidthX

- src/opentype.js
I've made an extra configuration change. I added support to pass isUrl (boolean) in opt parameter. If passed true it will allow user to load font from an http url in node environment as well.
I myself was using the library and needed to load font from url in backend code written in node js. So now this will help user to use urls even in backend code. And previous behaviour is preserved.
> Added the support of loading from http url in node environment.

- src/types.js
- test/types.js
If `undefined` is passed as the argument for `encode.CHARSET` or `sizeOf.CHARSET`, treat it as an empty string.
Some fonts contain (or are at least parsed with) glyphs whose name is `undefined`. Saving these fonts will fail with the following error:
> Uncaught TypeError: Cannot read property 'length' of undefined
>     at encode.CHARARRAY (types.js:71)
>     at Object.encode.OBJECT (types.js:871)
>     at Object.encode.INDEX (types.js:710)
>     at sizeOf.INDEX (types.js:739)
>     at Object.sizeOf.TABLE (types.js:946)
>     at Table.sizeOf (table.js:47)
>     at Object.makeCFFTable [as make] (cff.js:1301)
>     at Object.fontToSfntTable [as fontToTable] (sfnt.js:288)
>     at Font.toTables (font.js:483)
>     at Font.toArrayBuffer (font.js:497)
> 
I'll create this PR as a draft for …
> Handle undefined chararray

- src/tables/cff.js
- test/tables/cff.js
This PR fix the relative-coordinate error propagation found in the Quadratic to Cubic conversion stage of the CFF table ops building.
CFF does not support Quadratic command so `glyphToOps` generate a rounded Cubic Op which later create a coordinate deviations for every following commands.
This fix https://github.com/opentypejs/opentype.js/issues/467
I tested this change on ~110 quadratic scenarios and it gives me a much better result than before.
Draw 3 coordinate-identical quadratic curves (`M0,0 Q1,3,2,0 M0,0 Q1,3,2,0 M0,0 Q1,3,2,0`)
Before : the rounding error propagation shift every curves :negative_squared_cross_mark: 
After : the 3 identical curve exactly overlap :heavy_check_mark:
> Fix Quadratic to Cubic rounding issue in Glyph to CFF Ops stage

- src/util.js
See Issue #473. Running the sample code, shows a warning. This PR fixes the code to update to the new node Buffer API.
> Update to use Buffer.alloc in place of deprecated new Buffer()

- test/tables/gsub.js
Based on the tests I added for writing lookup type 6 format 1 and 3 tables, I also added the missing tests for the parsing side of the functionality.
Although parsing of those tables was supported for quite some time, there were never tests to cover the functionality, because the specs didn't provide examples.
Ran all tests.
_(not applicable, tests only)_
> add tests for parsing lookup type 6 formats 1 and 3

- README.md
- src/glyph.js
- test/glyph.js
This is the proposed solution for #500, wherein the leftSideBearing option should be supported by `bindConstructorValues`, allowing the value to be set from within the constructor.
Before that, the `leftSideBearing` property had to be manually assigned after constructing the object (see issue #500 for details).
A test case in `test/glyph.js` has been added, checking that the value is correctly set from the `options` object.
> Add option for leftSideBearing in new Glyph

- src/types.js
Replaces instances of `d = d.concat(...)` with `push` within encoding functions for improved performance per #512.  Should not impact results. 
This version is faster, particularly on Firefox.  As a test, I ran `window.font.download()` in the console of the https://opentype.js.org/ site.  In Firefox the change reduced runtime from 1,341ms to 190ms.  Chrome experienced a more modest improvement from 203ms to 166ms.  The ability to quickly generate custom font files is important for my project [Scribe OCR](https://github.com/Balearica/scribeocr), and I'm sure others as well. 
The unit tests pass and I am using this version in my live site.  Additionally, the change is conceptually simple and narrow in scope. 
- [x ] Bug fix (non-breaking change which fixes an issue)
> Replaced concat with push for performance

- src/tables/meta.js
As described in  #522: Attempting to parse certain fonts that define `appl` and `bild` tags in the `meta` tabke crashes Google Chrome/Chromium/Safari with "RangeError: Maximum call stack size exceeded."
See the detailed explanation in the issue. The font loads on the page served with `npm start` and this version of the code.
* instead of dropping the known incompatible/non-ASCII tags (`appl`, `bild`), we could drop all tags that are unknown (not `dlng`, `slng`)
* instead of dropping the tags, we could keep them, but use the un-parsed binary data. This way, the font could be re-build again without loss
> Don't attempt to parse meta table tags "appl" and "bild". Fixes #522

- src/opentype.js
WOFF2 is becoming more and more popular and is now the default font format in font.google.com
So Opentype.js is more and more expected to parse and generate WOFF2.
However WOFF2 compression (as WASM) would bloat the opentype.js dist file by ~1400 KB.
A more modular approach would be to let the end-user do the WOFF compress/decompress wrapping if they need it.
This PR aim to solve this lack of support by pointing the user to [a wrapping example](https://github.com/opentypejs/opentype.js/issues/183#issuecomment-1147228025) if they try the directly load a WOFF2 file into opentype.js
By loading a WOFF2 into opentype.js without decompresing it beforehand and looking at the reason given by the trown exception.
> Gracefully handle unsupported WOFF2 parsing

- site.css
Just a small visual fix for headlines following an expanded table section that only contains "Undefined" floating strangely.
While fixing something in the font inspector (`npm run start`), I noticed that headlines following a section that only contains "Undefined" in the definition list were floating next to the word.
Only affects the font inspector.
After the fix:
NOT APPLICABLE AS IT ONLY AFFECTS THE FONT INSPECTOR USED FOR TESTING
> font inspector: fix headline floating when table section with "Undefined" is expanded

- .jscsrc
- .jshintignore
I noticed that that jscs showed messages about files in the /.git directory (e.g. WIP files from local branches), so I added it to the ignore lists of both jscs and jshint.
> make jshint and jscs ignore the /.git folder

- src/tables/cff.js
- test/tables/cff.js
see #524
Fixes #524
Loaded *FiraSansOT-Medium.otf* before and after: former `undefined` entries are now the corresponding CID instead.
> make cffEncoding.charset fall back to CIDs instead of undefined

- src/table.js
- src/tables/gsub.js
- src/types.js
- test/table.js
- test/tables/gsub.js
* Preliminary work
* Writing support
* Tests
<s>Since Chaining Contextual Substitution is based on Contextual Substitution, I'll probably also add writing support for the last missing lookup type 6 format 2</s> Let's not make this more bloated than it already is and stick to one lookup type.
Filling the gaps of the last missing GSUB lookup/format types
Added tests according to the Microsoft spec examples, checked to not break any preexisting tests, tested different fonts.
> GSUB writing support for lookup type 5

- src/font.js
- test/font.js
adresses #574 
I tested it with my quite larger app, it works, it's quite a trivial change tough.
No I didn't, I tested it with my application.
charToGlyphIndex() and nameToGlyphIndex() are also not mentenioned in the README, maybe we should add all?
> adding stringToGlyphIndexes()

- src/hintingtt.js
- src/tables/cff.js
Replaces all usage of modulus "% 2" with the bitwise AND operator "& 1"
Inspired by https://github.com/opentypejs/opentype.js/pull/569#discussion_r1114926698
Ran all tests (and asked ChatGPT if those statements are really interchangeable in JavaScript 😅)
> optimize performance by replacing modulus with bitwise operator

- src/features/featureQuery.js
- test/tables/gsub.js
_In featureQuery.js:chainingSubstitutionFormat3_
- Modify var types of subtable, lookup, and substitutionType to be lets so they can be mutated in the next step.
- Detect substitution type "71" which means lookup table type 7 and format 1. 
- When detected, mutate the substitution type and lookup method based on the linked extension subtable
- Finally update the subtable variable to be the extension table
- Throw an error if the chained substitution type is not handled. This will avoid fonts that use chaining substitutions from silently rendering incorrectly if they use an unhandled changed substitution.
_In featureQuery.js:FeatureQuery.prototype.lookupFeature_
Same changes as above.
Addresses issue #415 
GSUB tables have a lookup table type 7 called the Extension Substitution Subtable. …
> GSUB lookup table type 7 subtable format 1

- src/opentype.js
- src/parse.js
- src/substitution.js
- src/tables/avar.js
- src/tables/fvar.js
- src/tables/gvar.js
- src/tables/sfnt.js
- src/tables/stat.js
- src/types.js
- src/util.js
- test/tables/avar.js
- test/tables/fvar.js
- test/tables/stat.js
- test/types.js
This PR lays the groundwork for variable fonts support. Actual coordinate scaling and normalization (see https://learn.microsoft.com/en-us/typography/opentype/spec/otvaroverview#CSN) for rendering is not yet implemented, but several tables needed for supporting it can now be parsed and written.
I decided against also implementing `gvar`, because it introduces a set of new concepts/data types and seems to be the most complex of them. That would have bloated the PR even more.
* arrowtype/blog/issues/6
* https://www.axis-praxis.org/samsa/
Loading and saving different variable fonts, added tests.
> Parsing and writing support for variable font tables fvar, STAT and avar

- src/features/arab/arabicRequiredLigatures.js
- src/features/latn/latinLigatures.js
- src/tables/gvar.js
- test/tables/avar.js
- test/tables/stat.js
adds missing import file extensions
While reviewing #353, I noticed that some imports were still missing the file extension that we need now after changing the build system and allowing the library to work in module form in browser context. While I was at it, I also added TODO comments for something we need to address after #564 is merged.
> add missing import file extensions, add @TODO comments for refactoring

- src/glyphset.js
- src/opentype.js
- src/parse.js
- src/tables/cff.js
- test/parse.js
- test/tables/cff.js
fix #249 
* add parsers that can be shared by other variable font related tables
* add operators for CFF2 table parsing
* parse glyph data in its default form, ignoring variations
* add some preparations for later variable font support
This PR does not handle font variation itself - it allows to load the data including glyph outlines and all other data from the CFF2 table. The glyphs will have their default form without any variations, so advanceWith will com from the glyph outline. But together with #576 it is an important step on the way to adding support for modern variable fonts.
CFF2 offers even better compression and is oprimized for variable fonts. Many variable fonts use CFF2 and couldn't be loaded before.
Added tests for the different parsers as well as parsing of the exampler …
> implement CFF2 parsing

- src/opentype.js
- src/tables/gasp.js
- src/tables/sfnt.js
- test/tables/gasp.js
Adding support for gasp table.
**makeGaspTable does not work, yet.** 
This pull request is for getting feedback from other people to make it work.
This font table was not supported, yet.
Added unittests
> gasp table

- src/glyph.js
- test/glyph.js
Resolve the problem of invalid unicodes input parameters
When attempting to instantiate a Glyph object with multiple values in the options.unicodes parameter, the input does not take effect and instead becomes [unicode].
To enable the 'unicodes' parameter
```javascript
const glyphOptions = {
"index": 3548,
"xMin": 58,
"xMax": 947,
"yMax": 825,
"unicode": 12101,
"unicodes": [
12101,
26041
],
"advanceWidth": 1000,
"leftSideBearing": 58,
"name": "方",
}
const glyph = new opentype.Glyph(glyphOptions)
// It will be [ 12101, 26041 ]
console.log('glyph :>> ', glyph.unicodes);
```
> fix(glyph): Resolve the problem of invalid unicodes input parameters

- package-lock.json
- package.json
Update all dependencies to their latest versions, except mocha for which we are still stuck at 8.4.0 (see #579).
Outdated versions had some vulnerabilities (see e.g. #628).
Ran `npm run build`, `npm run lint`, `npm run test` and `npm run start`
> bump all dependency versions except mocha

- src/parse.js
- src/types.js
- test/parse.js
- test/types.js
add tests for parsing and encoding the LONGDATETIME type
This was not tested before, and a FIXME comment suggested to do so once it was implemented (which it has been for a long time).
> add tests for LONGDATETIME parsing/encoding

- src/font.js
- test/font.js
For fonts using CMAP, `hasChar()` would always return `true`, even if the char was not contained. This wasn't caught because there was no corresponding test.
Fixes #330
Added a new test loading the existing CMAP test font and checking the `hasChar()` return values for existing and non-existing chars.
> fix hasChar() for CMAP fonts and add tests (fix #330)

- src/tables/sfnt.js
- test/font.js
- test/tables/sfnt.js
Fixed how a font's `preferredSubfamily` is set.
Currently in the `tables/sfnt.js` file inside `fontToSfntTable`, when setting a font's `preferredSubfamily` it's looking for `preferredSubFamily`, so if it's not already set it will always be `undefined`. Changed the `F` to an `f`
Fixes `undefined` preferredSubfamily if it's not explicitly set
Testing a feature from this [repo/site](https://github.com/eigilnikolajsen/commit-mono). which parses font files which does not have `macintosh.preferredSubfamily` set, but has `windows.preferredSubfamily` set. Specifically fonts from [here](https://github.com/eigilnikolajsen/commit-mono/tree/main/src/fonts/fontlab).  Launched the site locally using a simple http server and ran the customization feature from the site, while testing how the font …
> fix setting preferred subfamily

- docs/benchmark.html
This PR add a per-version performance comparison tool.
This tool will help us quantify performance gain/loss between the current /src/ build and the last master build (or any previous version built).
Tested on `npm start` and opening `/docs/benchmark.html` on chromium
> Add version performance benchmark tool

- src/path.js
Implement caching for decimal rounding by storing the results for the decimal part of floats only and adding them to the significant part. Also avoid unnecessary recalculations by storing the value for reuse.
fixes #641 
Using our performance test tool, we could see a huge drop (~1s vs ~6s) in performance from 1.3.4 to the current master. The culprit seems to have been the function `roundDecimal()` in `path.js` alone. That calculation seems to be very performance-hungry, however, it's the only way that I found so far to get reliable rounding of floats without losing precision.
Using the performance test tool in `docs/benchmark.html` comparing to version 1.3.4 before and after the optimization. Also ran `npm run test` as well as the unicode test tool to make sure it doesn't break passing …
> performance: implement caching for roundDecimal() and prevent unnecessary recalculations

- src/util.js
Made browser/node context detection more reliable, so we'll pick the correct loading methods even when running in a WebWorker context.
close #174 
Can't really add a test for this, but checked that our tests (= Node) and docs (= Browser) still work
> better browser/node detection

- src/tables/cmap.js
- test/opentypeSpec.js
I introduced a bug with my PR #338, this is the fix for it. We always want to take the first CMAP table that we support, but keep on looking for an optional format 14 table that will be applied separately (this is the only exception, all other CMAP tables are exclusive). But I forgot to check if we already found a CMAP table when setting the offset for the supported table format, so it kept overriding the selected table until it found a format 14 table, thus always using the last instead of the first supported table.
fix #649, this bug broke the unicode test suite tests CFF-1 and CFF-2, and probably other fonts as well.
loaded the FDArray test fonts and checked if the chars that broke in the test suite are displayed as expected
> fix cmap table selection (fix #649)

- src/tables/cmap.js
Replaces instances of `d = d.concat(...)` with `push` within `cmap` functions for improved performance per https://github.com/opentypejs/opentype.js/issues/682. Should not impact results.  Conceptually speaking, this is almost identical to #513.
Additionally, `t.segments.sort` was being run *every time* a new element was added within a loop; I edited to only run once after all elements are inserted. 
See #682.  In short, the performance of `font.toArrayBuffer()` can be poor, including >30+ second runtimes for certain large fonts.  This PR fixes that.
On my system (Chrome, Windows 10), this PR reduces the runtime for writing NotoSansSC from 36 seconds to 8 seconds (78% reduction), and reduces the runtime for NotoSerifSC from 33 seconds to 8 seconds (76% reduction).  
The unit tests pass …
> Replaced concat with push for better performance per #682

- src/util.js
- test/util.js
> Fix keys retrieval in objectsEqual function

- src/tables/sfnt.mjs
- test/tables/sfnt.spec.mjs
Due to a change in 858a5d2, fonts that are created from scratch are not generating two default name table entries, which is causing fonts to be un-openable in Windows.
Lots of details captured in #757 - but here is a quick overview of the bug. The bug that was causing issues for two reasons:
1) the `for... in` loop is looping over the keys of the array, `0, 1, 2` as opposed to the values of the array (which looks like what was intended).
2) If an empty value is found, the `unicode` value is updated as opposed to whatever platform is currently being looped over.
Any font object generated programmatically would successfully export, but the font file itself would not be able to be opened. In Windows the "This is not a valid font file" dialog would be shown.
Lots of tests explained in #757
> Bug fix for #757 - write all name table entries for fonts crafted from scratch

- src/glyphset.mjs
Calling `font.glyphs.get(9999)` should return `undefined` if the glyph doesn't exist.
When not in low memory mode, `font.glyphs.get(9999)` errors because `font._push` is undefined.
> GlyphSet.prototype.get can return undefined

- src/opentype.mjs
- src/tables/gasp.mjs
- test/tables/gasp.spec.mjs
See #738.  In short, write support for the `gasp` table was implemented recently in #595, however is broken.  Any font written by opentype.js that includes a `gasp` table cannot be re-imported by opentype.js.  
This PR makes two changes to resolve.  First, it fixes the typo in the `gasp` write function, which was trying to iterate over the integer `gasp.numRanges` rather than the array `gasp.gaspRanges`.  Second, it wraps the entire `gasp` read function in a `try` block.  This should prevent any future issues where failing to parse this optional table prevents a font from being read.  
I confirmed that the [Changa-Regular.ttf](https://github.com/opentypejs/opentype.js/blob/master/test/fonts/Changa-Regular.ttf) font could be saved/read using `toArrayBuffer`/`opentype.parse`, which (as …
> Fixed gasp support bugs per #738
